### ISSUE TITLE
MERN Stack Project

### ISSUE THREAD

**Issue by Alex96412** [Alex96412/MERN-Stater#1]
Hello, everyone.
Thanks for reaching out this issue.
I am new to web development.
Now I am studying MERN Stack.
I want to know how to start MERN Stack Development.
Any help is appreciated.

**Comment by Alex96412** [comment]
Hello, @Alex96412 👋
Please refer to this project.
<a href="https://github.com/bradtraversy/devconnector_2.0" >Brad Traversy's Repo(Social network for developers, built on the MERN stack)</a>
<br/>
<a href="https://freecoursesite.com/mern-stack-course-2023-mongodb-express-react-and-nodejs">MERN Stack Course</a>

**Comment by ronaldtech051** [comment]
Hello, @Alex96412 👋
Please refer to this project.
<ul>
<li><a href="https://github.com/bradtraversy/devconnector_2.0" >Brad Traversy's Repo(Social network for developers, built on the MERN stack)</a></li>
<li><a href="https://freecoursesite.com/mern-stack-course-2023-mongodb-express-react-and-nodejs">MERN Stack Course</a></li>
</ul>

**Comment by Alex96412** [comment]
> Hello, @Alex96412 👋 Please refer to this project.
> 
> * [Brad Traversy's Repo(Social network for developers, built on the MERN stack)](https://github.com/bradtraversy/devconnector_2.0)
> * [MERN Stack Course](https://freecoursesite.com/mern-stack-course-2023-mongodb-express-react-and-nodejs)

Thank you for your quick reply!
